apiVersion: apps/v1
kind: Deployment
metadata:
  name: bendrocorp-app-v4-deployment
spec:
  selector:
    matchLabels:
      app: bendrocorp-app-v4-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: bendrocorp-app-v4-deployment
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: bendrocorp-app-v1-deployment
        image: ghcr.io/bendrocorp/bendrocorp-app-v4:latest #VERSION_HERE
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: github-docker-secret